name: Deploy CloudFormation Guardrail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validate Code & Template
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install boto3

      - name: Lint Lambda function
        run: |
          pip install black flake8
          black --check lambda_function/
          flake8 lambda_function/

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://template.yaml

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: validate
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::111111111111:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Package Lambda function
        run: |
          cd lambda_function
          zip -r ../lambda_function.zip .
          cd ..

      - name: Upload Lambda code to S3
        run: aws s3 cp lambda_function.zip s3://source-bucket-name/lambda_function.zip

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name sqs-guardrail-stack \
            --template-file template.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaRuntime=python3.9 \
              LambdaMemorySize=128 \
              PermissionBoundaryArn=arn:aws:iam::111111111111:policy/BoundaryPolicy \
              ControlIdentifier=arn:aws:controltower:us-east-1::control/required-dlq \
              TargetIdentifier=arn:aws:organizations::111111111111:ou/o-xxxxxx/ou-yyyyy